### ISSUE TITLE
About data processing, and some possible problems and solutions

### ISSUE THREAD

**Issue by Mike001-wq** [XJay18/NeuMA#1]
Can you give the data organization format or data architecture in the Dynamics Grounding step? Or give the data preprocessing code?

**Comment by XJay18** [comment]
Hi! We implemented two types of data loaders, so there are two compatible structures for data storage. You can download our data to see the structures we used. If you just want an overview of these data structures, you may see the information below.
1. [NeuMASynthetic](https://github.com/XJay18/NeuMA/blob/058d04d4d1a0ba9a5d44ac02981d063c327c5dcd/modules/d3gs/scene/dataset_readers.py#L200)
```
# NOTE: 'optional' means only used for evaluation, not for dynamics grounding (or training)
.
|-- data
|    |-- BouncyBall
|    |    |-- data_dynamic      # directory for video frames depicting the object's motion
|    |    |    |-- d_X_YYY.png  # 'd' for 'dynamic', 'X' for the index of camera view, and 'YYY' for the time step
|    |    |    └── ... 
|    |    |-- data_dynamic.json # camera pose for each frame in 'data_dynamic'
|    |    |-- data_static       # directory for multi-view static captures of the object at the initial time step
|    |    |    |-- s_X_YYY.png  # 's' for 'static', 'X' for the index of camera view, and 'YYY' for the time step
|    |    |    └── ... 
|    |    |-- data_static.json  # camera pose for each frame in 'data_static'
|    |    |-- eval_dynamic      # directory for video frames depicting the object's motion for evaluation (optional)
|    |    |    |-- e_X_YYY.png  # 'e' for 'evaluation', 'X' for the index of camera view, and 'YYY' for the time step
|    |    |    └── ...
|    |    └── eval_dynamic.json # camera pose for each frame in 'eval_dynamic' (optional)
|    |-- ClayCat
|    └── ...
└── simulation_data             # directory for ground-truth particles (optional)
     |-- BouncyBall
     |    |-- YYY.ply           # 'YYY' for the time step
     |    └── ... 
     |-- ClayCat
     └── ... 

```
2. [RealCapture](https://github.com/XJay18/NeuMA/blob/058d04d4d1a0ba9a5d44ac02981d063c327c5dcd/modules/d3gs/scene/dataset_readers.py#L279)
```
.
|-- bun
|    |-- images                # directory for multi-view static captures of the object at the initial time step
|    |    |-- xxx.jpg
|    |    └── ... 
|    |-- masks                 # directory for binary foreground masks for each frame in 'images'
|    |    |-- xxx.png
|    |    └── ... 
|    |-- dynamics              # directory for video frames depicting the object's motion
|    |    |-- r_X_Y.jpg        # 'X' for the index of camera view, and 'Y' for the time step
|    |    └── ... 
|    |-- dynamic_masks         # directory for binary foreground masks for each frame in 'dynamics'
|    |    |-- r_X_Y.png        # 'X' for the index of camera view, and 'Y' for the time step
|    |    └── ... 
|    |-- sparse                # directory for colmap results
|    |    └── 0
|    |         └── ... 
|    |-- cameras_calib.json    # camera pose
|-- burger
└── ... 
```

**Comment by Mike001-wq** [comment]
I have four places where errors are reported and need to be modified. If you have the same error, you can refer to it:
1. In the 1473 line of the miniconda/envs/dreamscene4d/lib/python3.10/site-packages/warp/context.py folder, add
```
if arg_type==None:
    continue
```
Because I found that when arg is return in the loop, arg_type is None, which will cause an error.
2. In the 103 line function of the modules/d3gs/gaussian_renderer/__init__.py file, add antialiasing=False, because the latest version of the gaussian splatting library has added new features.
3. In the function of the 367 line of the modules/tune/utils.py file, add a return value, otherwise it will report an error of "too many values ​​to unpack".
4. In line 114 of the modules/tune/utils.py file, an error message "Unrecognized option 'qp'" will be reported. This is a problem with the ffmpeg version. Please use conda to install ffmpeg instead of pip. When the cuda version is 12.0 and the GPU version is A40, ffmpeg==4.2.2 can solve the problem.

**Comment by XJay18** [comment]
Hi, thank you so much for sharing the above information related to dependency issues! I'll look into it and do some necessary updates.

Best wishes!
