### ISSUE TITLE
Gaussian Kernals and Particle Mesh data

### ISSUE THREAD

**Issue by llliuxy** [XJay18/NeuMA#3]
Thanks for your work! It seems the Gaussian Kernals and Particle Mesh ply file are not provided in your data link. Could you please give some instructions about how to generate gaussians and mesh ply file with images and masks or simply provide the data link? Where can I find assets? I have no idea how to download assets(particles and meshes ply) because I can only get SpringGausData.7z and NeuMA-Synthetic.7z. Thank you so much!

**Comment by XJay18** [comment]
Hi, thank you for your interest! Those assets can be downloaded through [this link](https://1drv.ms/f/c/3f1ccc11f481c100/EgQDL270OjxDmbXQhMB-IbcBwK89e2xQkpZCrWmlxsQC6A?e=GhJlH9). For usage instructions, please refer to the [readme](https://github.com/XJay18/NeuMA?tab=readme-ov-file#pretrained-neural-material-adaptors).

You can also generate those assets yourself; please refer to the discussion [here](https://github.com/XJay18/NeuMA/issues/2#issuecomment-2466244925) for some information.

**Comment by llliuxy** [comment]
Thank you for your reply and patience! It helps me a lot. I still have a small question about the input of function `prepare_simulation_data()` . If I want to use my own data to generate assets and only have images and masks, how can I get the init kernels because this function seems require gaussian kernels as input.

**Comment by XJay18** [comment]
In this case, you can try to use gaussian-splatting to reconstruct gaussian kernels from multi-view images. The procedure is well documented in their readme.

**Comment by llliuxy** [comment]
Thank you for your patience and kindness!
