### ISSUE TITLE
Is it possible to simulate forces in multiple directions, such as forces applied in the horizontal direction?

### ISSUE THREAD

**Issue by Mike001-wq** [XJay18/NeuMA#4]
The examples given only have trajectories moving in the vertical direction. Can you simulate movement in the horizontal direction? For example, rolling and colliding on a plane?

**Comment by XJay18** [comment]
Hi, you can modify the initial (linear or angular) velocity in the configuration files (e.g., [here](https://github.com/XJay18/NeuMA/blob/a3e8e663f864f4082dbc7b4cf3d8d515cd16f924/experiments/configs/demo/generalize-kunkun.yaml#L69-L71)) to create an effect that the object was thrown in the horizontal direction.
