### ISSUE TITLE
Training Appears Unstable on Real-World Data

### ISSUE THREAD

**Issue by llliuxy** [XJay18/NeuMA#5]
Thank you for your excellent work!

Regarding real-world data, I have noticed that for the objects `burger`, `pig`, and `dog` (excluding `bun`), the training crashes around `200` finetune steps when `read_mask_only` is set to `false` (error: `CUDA error 700 detected`). In your code, the `config` files for these three objects have `read_mask_only` set to `true` by default. This suggests that during the supervision phase, only mask data was used instead of color image data (I’m not sure if I understand this correctly).

Could you please clarify whether the metric data provided in your paper was supervised using color images or purely mask data? I would greatly appreciate your assistance in resolving my confusion!

Thank you!

**Comment by XJay18** [comment]
Hi, we used the provided configuration files in our experiments to report the results. The training issues you encountered with certain objects may stem from color discrepancies between images captured during the static and dynamic stages (and also note that images captured in the static stage do not observe the bottom of the object, so the reconstructed Gaussian kernels have random colors for the bottom part). This discrepancy complicates the optimization of the photometric loss.

After reviewing SpringGaus's paper, we found that they calculated the loss using masked images (i.e., `read_mask_only=True`), which proved helpful in our experiments. For more details about the data preparation procedure, please refer to Section 4.2 of SpringGaus's paper.

**Comment by llliuxy** [comment]
Thank you for your patience and kindness!
